# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# CLOJURE
# =============================================================================

  clojure:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - clojure

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  clojure:
